# Generated by Django 4.1.1 on 2022-09-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_create_homepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="banner_title",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
